class initialization
initialize

	uint16_t := #uint16.
	uint64_t := #uint64.
	uint8_t := #uint8.
	int32_t := #int32.
	uint32_t := #uint32.
	time_t := #int.
	pid_t := #int.
	bool := #Boolean.
	int8_t := #int8.
	int16_t := #int16.
	int64_t := #int64.
	uintptr_t := #'void *'.
	nn_iovec := NnIOVector.
	nn_pollfd := NnPollDescriptor.
	nn_msghdr := NnMsgHeader.
	nn_cmsghdr := NnCMsgHeader.
	nn_symbol_properties := NnSymbolProperties